resources:
  - name: res_est_0
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_vitae_0
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_animi_0
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_eaque
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_mollitia_0
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_harum_0
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_occaecati_0
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_assumenda_0
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_eius_0
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_omnis_0
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
pipelines:
  - name: pipeline_non_1
    steps:
      - name: step_veritatis_1
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputResources:
            - name: res_est_0
          affinityGroup: groupet
      - name: step_perferendis_2
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_veritatis_1
          inputResources:
            - name: res_omnis_0
            - name: res_assumenda_0
          affinityGroup: groupet
      - name: step_ratione_3
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_veritatis_1
            - name: step_perferendis_2
          inputResources:
            - name: res_eius_0
          affinityGroup: groupvoluptas
      - name: step_voluptatem_4
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_animi_0 "date1=$date"
            - write_output res_omnis_0 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_ratione_3
            - name: step_perferendis_2
            - name: step_veritatis_1
          outputResources:
            - name: res_animi_0
            - name: res_omnis_0
          affinityGroup: groupvoluptas
      - name: step_assumenda_5
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_occaecati_0 "date1=$date"
            - write_output res_est_0 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_perferendis_2
          inputResources:
            - name: res_animi_0
            - name: res_assumenda_0
            - name: res_eius_0
          outputResources:
            - name: res_occaecati_0
            - name: res_est_0
          affinityGroup: groupratione
      - name: step_voluptatem_6
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_ratione_3
            - name: step_veritatis_1
            - name: step_perferendis_2
            - name: step_voluptatem_4
          inputResources:
            - name: res_assumenda_0
            - name: res_est_0
          affinityGroup: groupratione
      - name: step_magnam_7
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_harum_0 "date1=$date"
            - write_output res_eaque "date1=$date"
            - write_output res_occaecati_0 "date1=$date"
            - write_output res_mollitia_0 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_perferendis_2
            - name: step_voluptatem_6
            - name: step_voluptatem_4
          outputResources:
            - name: res_harum_0
            - name: res_eaque
            - name: res_occaecati_0
            - name: res_mollitia_0
          affinityGroup: groupatque
      - name: step_perspiciatis_8
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_est_0 "date1=$date"
            - write_output res_mollitia_0 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_voluptatem_4
          inputResources:
            - name: res_vitae_0
            - name: res_eius_0
          outputResources:
            - name: res_est_0
            - name: res_mollitia_0
          affinityGroup: groupminus
      - name: step_minima_9
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_harum_0 "date1=$date"
            - write_output res_omnis_0 "date1=$date"
            - write_output res_mollitia_0 "date1=$date"
            - write_output res_vitae_0 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_assumenda_5
          inputResources:
            - name: res_eius_0
          outputResources:
            - name: res_harum_0
            - name: res_omnis_0
            - name: res_mollitia_0
            - name: res_vitae_0
          affinityGroup: groupassumenda
      - name: step_sunt_10
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_est_0 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_magnam_7
            - name: step_ratione_3
            - name: step_assumenda_5
            - name: step_perspiciatis_8
          inputResources:
            - name: res_mollitia_0
            - name: res_animi_0
            - name: res_eius_0
            - name: res_omnis_0
          outputResources:
            - name: res_est_0
          affinityGroup: groupassumenda
