resources:
  - name: res_sed_1
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_quas_2
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_omnis_3
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_dolor_4
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_voluptates_5
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_molestias_6
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_vitae_7
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_quidem_8
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_nulla_9
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: res_vero_10
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
pipelines:
  - name: pipeline_odio_1
    steps:
      - name: step_voluptatem_1
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_vero_10 "date1=$date"
            - write_output res_vitae_7 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          outputResources:
            - name: res_vero_10
            - name: res_vitae_7
          affinityGroup: grouprepudiandae
      - name: step_voluptates_2
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_voluptates_5 "date1=$date"
            - write_output res_vitae_7 "date1=$date"
            - write_output res_quidem_8 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_voluptatem_1
          inputResources:
            - name: res_vero_10
          outputResources:
            - name: res_voluptates_5
            - name: res_vitae_7
            - name: res_quidem_8
          affinityGroup: grouprepudiandae
      - name: step_optio_3
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_voluptates_5 "date1=$date"
            - write_output res_nulla_9 "date1=$date"
            - write_output res_quidem_8 "date1=$date"
            - write_output res_vero_10 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_voluptatem_1
            - name: step_voluptates_2
          outputResources:
            - name: res_voluptates_5
            - name: res_nulla_9
            - name: res_quidem_8
            - name: res_vero_10
          affinityGroup: grouprepudiandae
      - name: step_ut_4
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_voluptates_5 "date1=$date"
            - write_output res_sed_1 "date1=$date"
            - write_output res_vitae_7 "date1=$date"
            - write_output res_quas_2 "date1=$date"
            - write_output res_quidem_8 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_voluptates_2
          inputResources:
            - name: res_vero_10
          outputResources:
            - name: res_voluptates_5
            - name: res_sed_1
            - name: res_vitae_7
            - name: res_quas_2
            - name: res_quidem_8
          affinityGroup: groupet
      - name: step_voluptatibus_5
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_omnis_3 "date1=$date"
            - write_output res_dolor_4 "date1=$date"
            - write_output res_quidem_8 "date1=$date"
            - write_output res_vitae_7 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_optio_3
          inputResources:
            - name: res_sed_1
            - name: res_vero_10
            - name: res_quas_2
          outputResources:
            - name: res_omnis_3
            - name: res_dolor_4
            - name: res_quidem_8
            - name: res_vitae_7
          affinityGroup: groupet
      - name: step_nobis_6
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_vitae_7 "date1=$date"
            - write_output res_quas_2 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_voluptates_2
            - name: step_ut_4
            - name: step_voluptatem_1
            - name: step_optio_3
          inputResources:
            - name: res_omnis_3
            - name: res_sed_1
            - name: res_vero_10
          outputResources:
            - name: res_vitae_7
            - name: res_quas_2
          affinityGroup: groupet
      - name: step_aut_7
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_vitae_7 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_ut_4
            - name: step_voluptatem_1
            - name: step_voluptates_2
            - name: step_nobis_6
            - name: step_optio_3
          outputResources:
            - name: res_vitae_7
          affinityGroup: groupvoluptatem
      - name: step_illo_8
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_nulla_9 "date1=$date"
            - write_output res_molestias_6 "date1=$date"
            - write_output res_dolor_4 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_voluptatem_1
          inputResources:
            - name: res_quas_2
          outputResources:
            - name: res_nulla_9
            - name: res_molestias_6
            - name: res_dolor_4
          affinityGroup: groupvoluptatem
      - name: step_ducimus_9
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_vitae_7 "date1=$date"
            - write_output res_molestias_6 "date1=$date"
            - write_output res_dolor_4 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_voluptatibus_5
            - name: step_voluptates_2
          inputResources:
            - name: res_nulla_9
            - name: res_quidem_8
            - name: res_quas_2
            - name: res_sed_1
          outputResources:
            - name: res_vitae_7
            - name: res_molestias_6
            - name: res_dolor_4
          affinityGroup: groupodit
      - name: step_autem_10
        type: Bash
        execution:
          onExecute:
            - printenv
            - 'echo "Executing step on ${stepvar_id}"'
            - export date=$(date)
            - write_output res_dolor_4 "date1=$date"
            - write_output res_voluptates_5 "date1=$date"
            - write_output res_nulla_9 "date1=$date"
            - write_output res_vero_10 "date1=$date"
            - printenv
            - printenv
            - printenv
            - printenv
            - printenv
        configuration:
          inputSteps:
            - name: step_illo_8
            - name: step_nobis_6
            - name: step_aut_7
          inputResources:
            - name: res_omnis_3
            - name: res_quidem_8
          outputResources:
            - name: res_dolor_4
            - name: res_voluptates_5
            - name: res_nulla_9
            - name: res_vero_10
          affinityGroup: groupnon
