pipelines:
  - name: S_WF_016
    steps:
      - name: S_WF_016_001
        type: Bash
        execution:
          onExecute:
            - echo "Step 1 is running"
      - name: S_WF_016_002
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_016_001
        execution:
          onStart:
            - add_run_variables step_2_var="foo"
          onExecute:
            - echo "Step 2 is running"
      - name: S_WF_016_003
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_016_001
        execution:
          onStart:
            - add_run_variables step_3_var="bar"
          onExecute:
            - echo "Step 3 is running"
      - name: S_WF_016_004
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_016_002
            - name: S_WF_016_003
        execution:
          onExecute:
            - echo "step_2_var - ${step_2_var}"
            - echo "step_3_var - ${step_3_var}"
            - if [ "$step_2_var" != "foo" ]; then exit 1; fi
            - if [ "$step_3_var" != "bar" ]; then exit 1; fi
  - name: S_WF_017
    steps:
      - name: S_WF_017_001
        type: Bash
        execution:
          onExecute:
            - echo "Step 1 is running"
      - name: S_WF_017_002
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_017_001
          affinityGroup: some_ag
        execution:
          onStart:
            - add_run_variables step_2_node_id="${step_node_id}"
          onExecute:
            - echo "Step 2 is running"
      - name: S_WF_017_003
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_017_001
          affinityGroup: some_ag
        execution:
          onStart:
            - add_run_variables step_3_node_id="${step_node_id}"
          onExecute:
            - echo "Step 3 is running"
      - name: S_WF_017_004
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_017_002
            - name: S_WF_017_003
          affinityGroup: some_ag
        execution:
          onStart:
            - step_4_node_id="${step_node_id}"
          onExecute:
            - echo "step_2_node_id - ${step_2_node_id}"
            - echo "step_3_node_id - ${step_3_node_id}"
            - echo "step_4_node_id - ${step_4_node_id}"
            - if [ "$step_2_node_id" != "$step_4_node_id" ]; then exit 1; fi
            - if [ "$step_3_node_id" != "$step_4_node_id" ]; then exit 1; fi
  - name: S_WF_018
    steps:
      - name: S_WF_018_001
        type: Bash
        execution:
          onExecute:
            - echo "Step 1 is running"
      - name: S_WF_018_002
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_018_001
          affinityGroup: some_ag
        execution:
          onStart:
            - add_run_variables step_2_var="foo"
          onExecute:
            - echo "Step 2 is running"
      - name: S_WF_018_003
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_018_001
          affinityGroup: some_ag
        execution:
          onStart:
            - add_run_variables step_3_var="bar"
          onExecute:
            - echo "Step 3 is running"
      - name: S_WF_018_004
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_018_002
            - name: S_WF_018_003
          affinityGroup: some_ag
        execution:
          onExecute:
            - echo "step_2_var - ${step_2_var}"
            - echo "step_3_var - ${step_3_var}"
            - if [ "$step_2_var" != "foo" ]; then exit 1; fi
            - if [ "$step_3_var" != "bar" ]; then exit 1; fi
  - name: S_WF_019
    steps:
      - name: S_WF_019_1
        type: Bash
        execution:
          onStart:
            - add_run_variables step_1_var="step_1"
          onExecute:
            - echo "step 1 is running"
      - name: S_WF_019_2
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_019_1
          affinityGroup: ag_foo
          priority: 4
        execution:
          onStart:
            - echo "step_4_var - ${step_4_var}"
            - if [ "$step_4_var" != "step_4" ]; then exit 1; fi
            - add_run_variables step_2_var="step_2"
          onExecute:
            - echo "step 2 is running"
      - name: S_WF_019_3
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_019_1
          affinityGroup: ag_foo
          priority: 1
        execution:
          onStart:
            - echo "step_1_var - ${step_1_var}"
            - if [ "$step_1_var" != "step_1" ]; then exit 1; fi
            - add_run_variables step_3_var="step_3"
          onExecute:
            - echo "step 3 is running"
      - name: S_WF_019_4
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_019_1
          affinityGroup: ag_foo
          priority: 3
        execution:
          onStart:
            - echo "step_3_var - ${step_3_var}"
            - if [ "$step_3_var" != "step_3" ]; then exit 1; fi
            - add_run_variables step_4_var="step_4"
          onExecute:
            - echo "step 4 is running"
      - name: S_WF_019_5
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_019_2
            - name: S_WF_019_3
            - name: S_WF_019_4
          affinityGroup: ag_foo
          priority: 4
        execution:
          onStart:
            - echo "step_6_var - ${step_6_var}"
            - if [ "$step_6_var" != "step_6" ]; then exit 1; fi
            - add_run_variables step_5_var="step_5"
          onExecute:
            - echo "step 5 is running"
      - name: S_WF_019_6
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_019_2
            - name: S_WF_019_3
            - name: S_WF_019_4
          affinityGroup: ag_foo
          priority: 2
        execution:
          onStart:
            - echo "step_2_var - ${step_2_var}"
            - echo "step_3_var - ${step_3_var}"
            - echo "step_4_var - ${step_4_var}"
            - if [ "$step_2_var" != "step_2" ]; then exit 1; fi
            - if [ "$step_3_var" != "step_3" ]; then exit 1; fi
            - if [ "$step_4_var" != "step_4" ]; then exit 1; fi
            - add_run_variables step_6_var="step_6"
          onExecute:
            - echo "step 6 is running"
      - name: S_WF_019_7
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_019_5
            - name: S_WF_019_6
          affinityGroup: ag_foo
          priority: 2
        execution:
          onStart:
            - echo "step_1_var - ${step_1_var}"
            - echo "step_2_var - ${step_2_var}"
            - echo "step_3_var - ${step_3_var}"
            - echo "step_4_var - ${step_4_var}"
            - echo "step_5_var - ${step_5_var}"
            - echo "step_6_var - ${step_6_var}"
            - if [ "$step_1_var" != "step_1" ]; then exit 1; fi
            - if [ "$step_2_var" != "step_2" ]; then exit 1; fi
            - if [ "$step_3_var" != "step_3" ]; then exit 1; fi
            - if [ "$step_4_var" != "step_4" ]; then exit 1; fi
            - if [ "$step_5_var" != "step_5" ]; then exit 1; fi
            - if [ "$step_6_var" != "step_6" ]; then exit 1; fi
          onExecute:
            - echo "step 7 is running"
